<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository\Admin\Customer;

use Customize\Entity\Customer\CustomerSearchTemplate;
use Doctrine\ORM\QueryBuilder;
use Eccube\Entity\Member;
use Eccube\Repository\AbstractRepository;
use Eccube\Repository\QueryKey;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerSearchTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerSearchTemplateRepository extends AbstractRepository
{
    /**
     * CustomerSearchTemplateRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(
        RegistryInterface $registry
    ) {
        parent::__construct($registry, CustomerSearchTemplate::class);
    }

    /**
     * @param  \Eccube\Entity\Member $Member
     *
     * @return QueryBuilder
     */
    public function getAll(Member $Member)
    {

        $qb = $this->createQueryBuilder('o')
            ->where('o.Member is NULL')
            ->orWhere('o.Member = :Member')
            ->setParameter('Member', $Member);

        // Order By
        $qb->addOrderBy('o.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
