<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;


use Customize\Entity\Contact\ContactSubject;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ContactSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactSubjectRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ContactSubject::class);
    }

    /**
     * お問合せ件名の表示順を一つ上げる.
     *
     * @param ContactSubject $ContactSubject
     *
     * @throws \Exception 更新対象のお問合せ件名より上位のお問合せ件名が存在しない場合.
     */
    public function up(ContactSubject $ContactSubject)
    {
        $sortNo = $ContactSubject->getSortNo();
        $ContactSubject2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$ContactSubject2) {
            throw new \Exception(sprintf('%s より上位のお問合せ件名が存在しません.', $ContactSubject->getId()));
        }

        $ContactSubject->setSortNo($sortNo + 1);
        $ContactSubject2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ContactSubject);
        $em->persist($ContactSubject2);
        $em->flush();
    }

    /**
     * お問合せ件名の表示順を一つ下げる.
     *
     * @param ContactSubject $ContactSubject
     *
     * @throws \Exception 更新対象のお問合せ件名より下位のお問合せ件名が存在しない場合.
     */
    public function down(ContactSubject $ContactSubject)
    {
        $sortNo = $ContactSubject->getSortNo();
        $ContactSubject2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$ContactSubject2) {
            throw new \Exception(sprintf('%s より下位のお問合せ件名が存在しません.', $ContactSubject->getId()));
        }

        $ContactSubject->setSortNo($sortNo - 1);
        $ContactSubject2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ContactSubject);
        $em->persist($ContactSubject2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param ContactSubject $ContactSubject
     */
    public function save($ContactSubject)
    {
        if (!$ContactSubject->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $ContactSubject
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($ContactSubject);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param ContactSubject $ContactSubject
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($ContactSubject)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $ContactSubject->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($ContactSubject);
        $em->flush();
    }
}
