<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;


use Customize\Entity\Contact\Contact;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Contact::class);
    }

    /**
     * お問合せの表示順を一つ上げる.
     *
     * @param Contact $Contact
     *
     * @throws \Exception 更新対象のお問合せより上位のお問合せが存在しない場合.
     */
    public function up(Contact $Contact)
    {
        $sortNo = $Contact->getSortNo();
        $Contact2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$Contact2) {
            throw new \Exception(sprintf('%s より上位のお問合せが存在しません.', $Contact->getId()));
        }

        $Contact->setSortNo($sortNo + 1);
        $Contact2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($Contact);
        $em->persist($Contact2);
        $em->flush();
    }

    /**
     * お問合せの表示順を一つ下げる.
     *
     * @param Contact $Contact
     *
     * @throws \Exception 更新対象のお問合せより下位のお問合せが存在しない場合.
     */
    public function down(Contact $Contact)
    {
        $sortNo = $Contact->getSortNo();
        $Contact2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$Contact2) {
            throw new \Exception(sprintf('%s より下位のお問合せが存在しません.', $Contact->getId()));
        }

        $Contact->setSortNo($sortNo - 1);
        $Contact2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($Contact);
        $em->persist($Contact2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param Contact $Contact
     */
    public function save($Contact)
    {
        if (!$Contact->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $Contact
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($Contact);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param Contact $Contact
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($Contact)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $Contact->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($Contact);
        $em->flush();
    }
}
