<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Customer\CustomerClass;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerClassRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerClass::class);
    }

    /**
     * 会員区分の表示順を一つ上げる.
     *
     * @param CustomerClass $CustomerClass
     *
     * @throws \Exception 更新対象の区分より上位の区分が存在しない場合.
     */
    public function up(CustomerClass $CustomerClass)
    {
        $sortNo = $CustomerClass->getSortNo();
        $CustomerClass2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$CustomerClass2) {
            throw new \Exception(sprintf('%s より上位の会員区分が存在しません.', $CustomerClass->getId()));
        }

        $CustomerClass->setSortNo($sortNo + 1);
        $CustomerClass2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($CustomerClass);
        $em->persist($CustomerClass2);
        $em->flush();
    }

    /**
     * 会員区分の表示順を一つ下げる.
     *
     * @param CustomerClass $CustomerClass
     *
     * @throws \Exception 更新対象の区分より下位の区分が存在しない場合.
     */
    public function down(CustomerClass $CustomerClass)
    {
        $sortNo = $CustomerClass->getSortNo();
        $CustomerClass2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$CustomerClass2) {
            throw new \Exception(sprintf('%s より下位の会員区分が存在しません.', $CustomerClass->getId()));
        }

        $CustomerClass->setSortNo($sortNo - 1);
        $CustomerClass2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($CustomerClass);
        $em->persist($CustomerClass2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param CustomerClass $CustomerClass
     */
    public function save($CustomerClass)
    {
        if (!$CustomerClass->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $CustomerClass
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($CustomerClass);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param CustomerClass $CustomerClass
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($CustomerClass)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $CustomerClass->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($CustomerClass);
        $em->flush();
    }
}
