<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Customer\CustomerClass;
use Eccube\Common\EccubeConfig;
use Eccube\Entity\GiftAddress;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * GiftAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftAddressRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry,EccubeConfig $eccubeConfig)
    {
        parent::__construct($registry, GiftAddress::class);
        $this->eccubeConfig = $eccubeConfig;
    }

    /**
     * 登録.
     *
     * @param GiftAddress $GiftAddress
     */
    public function save($GiftAddress)
    {
        if (!$GiftAddress->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $GiftAddress
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($GiftAddress);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param GiftAddress $GiftAddress
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($GiftAddress)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $GiftAddress->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($GiftAddress);
        $em->flush();
    }
}
