<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Product\ProductExtensionItem;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ProductExtensionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductExtensionItemRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductExtensionItem::class);
    }

    /**
     * メーカーの表示順を一つ上げる.
     *
     * @param ProductExtensionItem $ProductExtensionItem
     *
     * @throws \Exception 更新対象のメーカーより上位のメーカーが存在しない場合.
     */
    public function up(ProductExtensionItem $ProductExtensionItem)
    {
        $sortNo = $ProductExtensionItem->getSortNo();
        $ProductExtensionItem2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$ProductExtensionItem2) {
            throw new \Exception(sprintf('%s より上位のメーカーが存在しません.', $ProductExtensionItem->getId()));
        }

        $ProductExtensionItem->setSortNo($sortNo + 1);
        $ProductExtensionItem2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductExtensionItem);
        $em->persist($ProductExtensionItem2);
        $em->flush();
    }

    /**
     * メーカーの表示順を一つ下げる.
     *
     * @param ProductExtensionItem $ProductExtensionItem
     *
     * @throws \Exception 更新対象のメーカーより下位のメーカーが存在しない場合.
     */
    public function down(ProductExtensionItem $ProductExtensionItem)
    {
        $sortNo = $ProductExtensionItem->getSortNo();
        $ProductExtensionItem2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$ProductExtensionItem2) {
            throw new \Exception(sprintf('%s より下位のメーカーが存在しません.', $ProductExtensionItem->getId()));
        }

        $ProductExtensionItem->setSortNo($sortNo - 1);
        $ProductExtensionItem2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductExtensionItem);
        $em->persist($ProductExtensionItem2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param ProductExtensionItem $ProductExtensionItem
     */
    public function save($ProductExtensionItem)
    {
        if (!$ProductExtensionItem->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $ProductExtensionItem
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($ProductExtensionItem);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param ProductExtensionItem $ProductExtensionItem
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($ProductExtensionItem)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $ProductExtensionItem->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($ProductExtensionItem);
        $em->flush();
    }
}
