<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Product\ProductIcon;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ProductIconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductIconRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductIcon::class);
    }

    /**
     * メーカーの表示順を一つ上げる.
     *
     * @param ProductIcon $ProductIcon
     *
     * @throws \Exception 更新対象のメーカーより上位のメーカーが存在しない場合.
     */
    public function up(ProductIcon $ProductIcon)
    {
        $sortNo = $ProductIcon->getSortNo();
        $ProductIcon2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$ProductIcon2) {
            throw new \Exception(sprintf('%s より上位のメーカーが存在しません.', $ProductIcon->getId()));
        }

        $ProductIcon->setSortNo($sortNo + 1);
        $ProductIcon2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductIcon);
        $em->persist($ProductIcon2);
        $em->flush();
    }

    /**
     * メーカーの表示順を一つ下げる.
     *
     * @param ProductIcon $ProductIcon
     *
     * @throws \Exception 更新対象のメーカーより下位のメーカーが存在しない場合.
     */
    public function down(ProductIcon $ProductIcon)
    {
        $sortNo = $ProductIcon->getSortNo();
        $ProductIcon2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$ProductIcon2) {
            throw new \Exception(sprintf('%s より下位のメーカーが存在しません.', $ProductIcon->getId()));
        }

        $ProductIcon->setSortNo($sortNo - 1);
        $ProductIcon2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductIcon);
        $em->persist($ProductIcon2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param ProductIcon $ProductIcon
     */
    public function save($ProductIcon)
    {
        if (!$ProductIcon->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $ProductIcon
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($ProductIcon);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param ProductIcon $ProductIcon
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($ProductIcon)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $ProductIcon->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($ProductIcon);
        $em->flush();
    }

    public function getAllIconId($ProductIcons)
    {
        $ids = [];
        foreach ($ProductIcons as $ProductIcon) {
            $ids[] = $ProductIcon->getId();
        }
        return $ids;
    }
}
