<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Product\ProductGenre;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ProductSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGenreRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ProductGenre::class);
    }

    /**
     * メーカーの表示順を一つ上げる.
     *
     * @param ProductGenre $ProductGenre
     *
     * @throws \Exception 更新対象のメーカーより上位のメーカーが存在しない場合.
     */
    public function up(ProductGenre $ProductGenre)
    {
        $sortNo = $ProductGenre->getSortNo();
        $ProductGenre2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$ProductGenre2) {
            throw new \Exception(sprintf('%s より上位のメーカーが存在しません.', $ProductGenre->getId()));
        }

        $ProductGenre->setSortNo($sortNo + 1);
        $ProductGenre2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductGenre);
        $em->persist($ProductGenre2);
        $em->flush();
    }

    /**
     * メーカーの表示順を一つ下げる.
     *
     * @param ProductGenre $ProductGenre
     *
     * @throws \Exception 更新対象のメーカーより下位のメーカーが存在しない場合.
     */
    public function down(ProductGenre $ProductGenre)
    {
        $sortNo = $ProductGenre->getSortNo();
        $ProductGenre2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$ProductGenre2) {
            throw new \Exception(sprintf('%s より下位のメーカーが存在しません.', $ProductGenre->getId()));
        }

        $ProductGenre->setSortNo($sortNo - 1);
        $ProductGenre2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($ProductGenre);
        $em->persist($ProductGenre2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param ProductGenre $ProductGenre
     */
    public function save($ProductGenre)
    {
        if (!$ProductGenre->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $ProductGenre
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($ProductGenre);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param ProductGenre $ProductGenre
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($ProductGenre)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $ProductGenre->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($ProductGenre);
        $em->flush();
    }
}
