<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Setting\PurchaseGroup;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * PurchaseGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseGroupRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, PurchaseGroup::class);
    }

    /**
     * 購入グループの表示順を一つ上げる.
     *
     * @param PurchaseGroup $PurchaseGroup
     *
     * @throws \Exception 更新対象の購入グループより上位の購入グループが存在しない場合.
     */
    public function up(PurchaseGroup $PurchaseGroup)
    {
        $sortNo = $PurchaseGroup->getSortNo();
        $PurchaseGroup2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$PurchaseGroup2) {
            throw new \Exception(sprintf('%s より上位の購入グループが存在しません.', $PurchaseGroup->getId()));
        }

        $PurchaseGroup->setSortNo($sortNo + 1);
        $PurchaseGroup2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($PurchaseGroup);
        $em->persist($PurchaseGroup2);
        $em->flush();
    }

    /**
     * 購入グループの表示順を一つ下げる.
     *
     * @param PurchaseGroup $PurchaseGroup
     *
     * @throws \Exception 更新対象の購入グループより下位の購入グループが存在しない場合.
     */
    public function down(PurchaseGroup $PurchaseGroup)
    {
        $sortNo = $PurchaseGroup->getSortNo();
        $PurchaseGroup2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$PurchaseGroup2) {
            throw new \Exception(sprintf('%s より下位の購入グループが存在しません.', $PurchaseGroup->getId()));
        }

        $PurchaseGroup->setSortNo($sortNo - 1);
        $PurchaseGroup2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($PurchaseGroup);
        $em->persist($PurchaseGroup2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param PurchaseGroup $PurchaseGroup
     */
    public function save($PurchaseGroup)
    {
        if (!$PurchaseGroup->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $PurchaseGroup
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($PurchaseGroup);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param PurchaseGroup $PurchaseGroup
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($PurchaseGroup)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $PurchaseGroup->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($PurchaseGroup);
        $em->flush();
    }
}
