<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Customize\Entity\Master\WithdrawalReason;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Repository\AbstractRepository;

/**
 * WithdrawalReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawalReasonRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, WithdrawalReason::class);
    }

     /**
     * メーカーの表示順を一つ上げる.
     *
     * @param WithdrawalReason $WithdrawalReason
     *
     * @throws \Exception 更新対象のメーカーより上位のメーカーが存在しない場合.
     */
    public function up(WithdrawalReason $WithdrawalReason)
    {
        $sortNo = $WithdrawalReason->getSortNo();
        $WithdrawalReason2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$WithdrawalReason2) {
            throw new \Exception(sprintf('%s より上位のメーカーが存在しません.', $WithdrawalReason->getId()));
        }

        $WithdrawalReason->setSortNo($sortNo + 1);
        $WithdrawalReason2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($WithdrawalReason);
        $em->persist($WithdrawalReason2);
        $em->flush();
    }

    /**
     * メーカーの表示順を一つ下げる.
     *
     * @param WithdrawalReason $WithdrawalReason
     *
     * @throws \Exception 更新対象のメーカーより下位のメーカーが存在しない場合.
     */
    public function down(WithdrawalReason $WithdrawalReason)
    {
        $sortNo = $WithdrawalReason->getSortNo();
        $WithdrawalReason2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$WithdrawalReason2) {
            throw new \Exception(sprintf('%s より下位のメーカーが存在しません.', $WithdrawalReason->getId()));
        }

        $WithdrawalReason->setSortNo($sortNo - 1);
        $WithdrawalReason2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($WithdrawalReason);
        $em->persist($WithdrawalReason2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param WithdrawalReason $WithdrawalReason
     */
    public function save($WithdrawalReason)
    {
        if (!$WithdrawalReason->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $WithdrawalReason
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($WithdrawalReason);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param WithdrawalReason $WithdrawalReason
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($WithdrawalReason)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $WithdrawalReason->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($WithdrawalReason);
        $em->flush();
    }
}
