<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Shipping;

use Customize\Entity\Shipping\ShippingGroup;
use Doctrine\ORM\QueryBuilder;
use Eccube\Entity\Template;
use Eccube\Repository\AbstractRepository;
use Eccube\Util\StringUtil;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ShippingGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingGroupRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ShippingGroup::class);
    }

    /**
     * Build query
     *
     * @param  array $searchData
     *
     * @return QueryBuilder
     *
     * @deprecated 使用していないので削除予定
     */
    public function getQueryBuilderBySearchDataForAdmin($searchData)
    {
        $qb = $this->createQueryBuilder('s');

        // payment_total
        if (isset($searchData['created_at']) && StringUtil::isNotBlank($searchData['created_at'])) {
            $qb
                ->andWhere('o.created_at >= :created_at')
                ->setParameter('payment_total_start', $searchData['created_at']);
        }

        // Order By
        $qb->orderBy('s.created_at', 'DESC');
        $qb->addorderBy('s.id', 'DESC');

        return $qb;
    }
}
