<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Master;


use Customize\Entity\Master\Course;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Course::class);
    }

    /**
     * 管理ユーザの表示順を一つ上げる.
     *
     * @param Course $Course
     *
     * @throws \Exception 更新対象のユーザより上位のユーザが存在しない場合.
     */
    public function up(Course $Course)
    {
        $sortNo = $Course->getSortNo();
        $Course2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$Course2) {
            throw new \Exception(sprintf('%s より上位の管理ユーザが存在しません.', $Course->getId()));
        }

        $Course->setSortNo($sortNo + 1);
        $Course2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($Course);
        $em->persist($Course2);
        $em->flush();
    }

    /**
     * 管理ユーザの表示順を一つ下げる.
     *
     * @param Course $Course
     *
     * @throws \Exception 更新対象のユーザより下位のユーザが存在しない場合.
     */
    public function down(Course $Course)
    {
        $sortNo = $Course->getSortNo();
        $Course2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$Course2) {
            throw new \Exception(sprintf('%s より下位の管理ユーザが存在しません.', $Course->getId()));
        }

        $Course->setSortNo($sortNo - 1);
        $Course2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($Course);
        $em->persist($Course2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param Course $Course
     */
    public function save($Course)
    {
        if (!$Course->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $Course
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($Course);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param Course $Course
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($Course)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $Course->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($Course);
        $em->flush();
    }
}
