<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Master;

use Customize\Entity\Master\CustomerRank;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CustomerRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRankRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerRank::class);
    }

    /**
     * 会員ランクの表示順を一つ上げる.
     *
     * @param CustomerRank $CustomerRank
     *
     * @throws \Exception 更新対象のユーザより上位のユーザが存在しない場合.
     */
    public function up(CustomerRank $CustomerRank)
    {
        $sortNo = $CustomerRank->getSortNo();
        $CustomerRank2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$CustomerRank2) {
            throw new \Exception(sprintf('%s より上位の会員ランクが存在しません.', $CustomerRank->getId()));
        }

        $CustomerRank->setSortNo($sortNo + 1);
        $CustomerRank2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($CustomerRank);
        $em->persist($CustomerRank2);
        $em->flush();
    }

    /**
     * 会員ランクの表示順を一つ下げる.
     *
     * @param CustomerRank $CustomerRank
     *
     * @throws \Exception 更新対象のユーザより下位のユーザが存在しない場合.
     */
    public function down(CustomerRank $CustomerRank)
    {
        $sortNo = $CustomerRank->getSortNo();
        $CustomerRank2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$CustomerRank2) {
            throw new \Exception(sprintf('%s より下位の会員ランクが存在しません.', $CustomerRank->getId()));
        }

        $CustomerRank->setSortNo($sortNo - 1);
        $CustomerRank2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($CustomerRank);
        $em->persist($CustomerRank2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param CustomerRank $CustomerRank
     */
    public function save($CustomerRank)
    {
        if (!$CustomerRank->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $CustomerRank
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($CustomerRank);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param CustomerRank $CustomerRank
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($CustomerRank)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $CustomerRank->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($CustomerRank);
        $em->flush();
    }
}
