<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Master;

use Customize\Entity\Master\DeliveryCalendar;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * DeliveryCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryCalendarRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, DeliveryCalendar::class);
    }

    /**
     * 配送カレンダーの表示順を一つ上げる.
     *
     * @param DeliveryCalendar $DeliveryCalendar
     *
     * @throws \Exception 更新対象のユーザより上位のユーザが存在しない場合.
     */
    public function up(DeliveryCalendar $DeliveryCalendar)
    {
        $sortNo = $DeliveryCalendar->getSortNo();
        $DeliveryCalendar2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$DeliveryCalendar2) {
            throw new \Exception(sprintf('%s より上位の配送カレンダーが存在しません.', $DeliveryCalendar->getId()));
        }

        $DeliveryCalendar->setSortNo($sortNo + 1);
        $DeliveryCalendar2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($DeliveryCalendar);
        $em->persist($DeliveryCalendar2);
        $em->flush();
    }

    /**
     * 配送カレンダーの表示順を一つ下げる.
     *
     * @param DeliveryCalendar $DeliveryCalendar
     *
     * @throws \Exception 更新対象のユーザより下位のユーザが存在しない場合.
     */
    public function down(DeliveryCalendar $DeliveryCalendar)
    {
        $sortNo = $DeliveryCalendar->getSortNo();
        $DeliveryCalendar2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$DeliveryCalendar2) {
            throw new \Exception(sprintf('%s より下位の配送カレンダーが存在しません.', $DeliveryCalendar->getId()));
        }

        $DeliveryCalendar->setSortNo($sortNo - 1);
        $DeliveryCalendar2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($DeliveryCalendar);
        $em->persist($DeliveryCalendar2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param DeliveryCalendar $DeliveryCalendar
     */
    public function save($DeliveryCalendar)
    {
        if (!$DeliveryCalendar->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $DeliveryCalendar
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($DeliveryCalendar);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param DeliveryCalendar $DeliveryCalendar
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($DeliveryCalendar)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $DeliveryCalendar->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($DeliveryCalendar);
        $em->flush();
    }
}
