<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Master;

use Customize\Entity\Master\FinancialInstitution;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * FinancialInstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialInstitutionRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, FinancialInstitution::class);
    }

    /**
     * 金融機関の表示順を一つ上げる.
     *
     * @param FinancialInstitution $FinancialInstitution
     *
     * @throws \Exception 更新対象の金融機関より上位の金融機関が存在しない場合.
     */
    public function up(FinancialInstitution $FinancialInstitution)
    {
        $sortNo = $FinancialInstitution->getSortNo();
        $FinancialInstitution2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$FinancialInstitution2) {
            throw new \Exception(sprintf('%s より上位の金融機関が存在しません.', $FinancialInstitution->getId()));
        }

        $FinancialInstitution->setSortNo($sortNo + 1);
        $FinancialInstitution2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($FinancialInstitution);
        $em->persist($FinancialInstitution2);
        $em->flush();
    }

    /**
     * 金融機関の表示順を一つ下げる.
     *
     * @param FinancialInstitution $FinancialInstitution
     *
     * @throws \Exception 更新対象の金融機関より下位の金融機関が存在しない場合.
     */
    public function down(FinancialInstitution $FinancialInstitution)
    {
        $sortNo = $FinancialInstitution->getSortNo();
        $FinancialInstitution2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$FinancialInstitution2) {
            throw new \Exception(sprintf('%s より下位の金融機関が存在しません.', $FinancialInstitution->getId()));
        }

        $FinancialInstitution->setSortNo($sortNo - 1);
        $FinancialInstitution2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($FinancialInstitution);
        $em->persist($FinancialInstitution2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param FinancialInstitution $FinancialInstitution
     */
    public function save($FinancialInstitution)
    {
        if (!$FinancialInstitution->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $FinancialInstitution
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($FinancialInstitution);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param FinancialInstitution $FinancialInstitution
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($FinancialInstitution)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $FinancialInstitution->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($FinancialInstitution);
        $em->flush();
    }
}
