<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\Master;

use Customize\Entity\Master\Pamphlet;
use src\Eccube\Entity\Master\Customer;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BulkBuyingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PamphletRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Pamphlet::class);
    }

    /**
     * まとめ買いグループの表示順を一つ上げる.
     *
     * @param Pamphlet $pamphlet
     *
     * @throws \Exception 更新対象のユーザより上位のユーザが存在しない場合.
     */
    public function up(Pamphlet $pamphlet)
    {
        $sortNo = $Pamphlet->getSortNo();
        $Pamphlet2 = $this->findOneBy(['sort_no' => $sortNo + 1]);

        if (!$Pamphlet2) {
            throw new \Exception(sprintf('%s より上位のまとめ買いグループが存在しません.', $Pamphlet->getId()));
        }

        $Pamphlet->setSortNo($sortNo + 1);
        $Pamphlet2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($Pamphlet);
        $em->persist($Pamphlet2);
        $em->flush();
    }

    /**
     * まとめ買いグループの表示順を一つ下げる.
     *
     * @param Pamphlet $pamphlet
     *
     * @throws \Exception 更新対象のユーザより下位のユーザが存在しない場合.
     */
    public function down(BulkBuying $bulkBuying)
    {
        $sortNo = $Pamphlet->getSortNo();
        $Pamphlet2 = $this->findOneBy(['sort_no' => $sortNo - 1]);

        if (!$Pamphlet2) {
            throw new \Exception(sprintf('%s より下位のまとめ買いグループが存在しません.', $Pamphlet->getId()));
        }

        $Pamphlet->setSortNo($sortNo - 1);
        $Pamphlet2->setSortNo($sortNo);

        $em = $this->getEntityManager();
        $em->persist($BulkBuying);
        $em->persist($BulkBuying2);
        $em->flush();
    }

    /**
     * 登録.
     *
     * @param Pamphlet $pamphlet
     */
    public function save($Pamphlet)
    {
        if (!$Pamphlet->getId()) {
            $sortNo = $this->createQueryBuilder('c')
                ->select('COALESCE(MAX(c.sort_no), 0)')
                ->getQuery()
                ->getSingleScalarResult();
            $Pamphlet
                ->setSortNo($sortNo + 1);
        }

        $em = $this->getEntityManager();
        $em->persist($Pamphlet);
        $em->flush();
    }

    /**
     * 削除.
     *
     * @param Pamphlet $pamphlet
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($Pamphlet)
    {
        $this->createQueryBuilder('c')
            ->update()
            ->set('c.sort_no', 'c.sort_no - 1')
            ->where('c.sort_no > :sort_no')
            ->setParameter('sort_no', $Pamphlet->getSortNo())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();

        $em->flush();

        $em->remove($Pamphlet);
        $em->flush();
    }
}
